#This file is used to enable renovate to update the digests. It is updated by renovate then substituted into the golang code.

FROM quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:ca69e8265ef0ab2486cb99419e6edafca3f78251591c99ece58589f048736cda
