apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- system-config.yaml

labels:
- includeSelectors: true
  pairs:
    app: hacbs-jvm-operator

#note that when updating the ref here you must also update system-config.yaml
patches:
- path: https://raw.githubusercontent.com/redhat-appstudio/jvm-build-service-builder-images/40ea46e49d006c98cc89609d6c0d356d13bf1502/image-config.yaml
