apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- system-config.yaml

labels:
- includeSelectors: true
  pairs:
    app: hacbs-jvm-operator

#note that when updating the ref here you must also update system-config.yaml
patches:
- path: https://raw.githubusercontent.com/redhat-appstudio/jvm-build-service-builder-images/c0f0ebc471ea1c7f233b0a15a7aea8852f8a08e8/image-config.yaml
