apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- system-config.yaml

labels:
- includeSelectors: true
  pairs:
    app: hacbs-jvm-operator

#note that when updating the ref here you must also update system-config.yaml
patches:
- path: https://raw.githubusercontent.com/redhat-appstudio/jvm-build-service-builder-images/07d98b880ec4074c0fafc26615fc4fa3380b3bf5/image-config.yaml

