---
apiVersion: jvmbuildservice.io/v1alpha1
kind: SystemConfig
metadata:
  name: cluster
spec:
  builders:
    #note that when updating the ref here you must also update kustomization.yaml
    ubi8:
      image: quay.io/redhat-user-workloads/rhtap-build-tenant/jvm-build-service-builder-images/ubi8:295418988fc1d5df7d6f888fa6a972ba10ae7258
      priority: 2000
    ubi7:
      image: quay.io/redhat-user-workloads/rhtap-build-tenant/jvm-build-service-builder-images/ubi7:295418988fc1d5df7d6f888fa6a972ba10ae7258
      priority: 1000
