---
apiVersion: jvmbuildservice.io/v1alpha1
kind: SystemConfig
metadata:
  name: cluster
spec:
  builders:
    #note that when updating the ref here you must also update kustomization.yaml
    ubi8:
      image: quay.io/redhat-appstudio/jbs-ubi8-builder:c0f0ebc471ea1c7f233b0a15a7aea8852f8a08e8
      priority: 2000
    ubi7:
      image: quay.io/redhat-appstudio/jbs-ubi7-builder:c0f0ebc471ea1c7f233b0a15a7aea8852f8a08e8
      priority: 1000
