---
apiVersion: jvmbuildservice.io/v1alpha1
kind: SystemConfig
metadata:
  name: cluster
spec:
  builders:
    #note that when updating the ref here you must also update kustomization.yaml
    ubi8:
      image: quay.io/redhat-appstudio/jbs-ubi8-builder:07d98b880ec4074c0fafc26615fc4fa3380b3bf5
      priority: 2000
    ubi7:
      image: quay.io/redhat-appstudio/jbs-ubi7-builder:07d98b880ec4074c0fafc26615fc4fa3380b3bf5
      priority: 1000
