---
apiVersion: jvmbuildservice.io/v1alpha1
kind: JBSConfig
metadata:
  name: jvm-build-config
spec:
  registry:
    owner: QUAY_USERNAME
  mavenDeployment:
    username: MAVEN_USERNAME
    repository: MAVEN_REPOSITORY
  relocationPatterns:
    - relocationPattern:
        buildPolicy: "default"
        patterns:
          - pattern:
              from: (io.github.stuartwdouglas.hacbs-test.simple):(simple-jdk17):(99-does-not-exist)
              to: io.github.stuartwdouglas.hacbs-test.simple:simple-jdk17:0.1.2
