apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jbs-management
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - jvmbuildservice.io
    resources:
      - artifactbuilds
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - jvmbuildservice.io
    resources:
      - jbsconfigs
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - tekton.dev
    resources:
      - taskruns/status
      - pipelineruns/status
      - taskruns/status
      - pipelineruns/status
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jbs-management
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jbs-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jbs-management
subjects:
  - kind: ServiceAccount
    name: jbs-management
---
apiVersion: v1
kind: Secret
metadata:
  name: jbs-management-secret
  annotations:
    kubernetes.io/service-account.name: jbs-management
type: kubernetes.io/service-account-token
