apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: quarkus-security-build-
spec:
  pipelineRef:
    name: sample-component-build
  params:
    - name: url
      value: https://github.com/quarkusio/quarkus-security.git
    - name: tag
      value: 1.1.4.Final
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
