apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacbs-jvm-operator
  namespace: jvm-build-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hacbs-jvm-operator
  template:
    metadata:
      labels:
        app: hacbs-jvm-operator
    spec:
      volumes:
        - name: quaytoken
          secret:
            optional: false
            secretName: quaytoken
      securityContext:
        runAsNonRoot: true
      containers:
        - name: hacbs-jvm-operator
          image: hacbs-jvm-operator:next
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http-metrics
          args:
            - "--v=4"
            - "--zap-log-level=info"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "50m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: "/workspace"
              name: quaytoken
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
      serviceAccountName: hacbs-jvm-operator
