apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: jvm-cli-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: 'quay.io/redhat-appstudio/hacbs-jvm-cli:latest' #this uses latest rather than a hash because it is a user consumable tool. It is not intended to be used by gitops
    - name: path-context
      value: java-components
    - name: dockerfile
      value: cli/src/main/docker/Dockerfile.all-in-one
    - name: slack-webhook-notification-team
      value: build
  pipelineRef:
    resolver: bundles
    params:
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/pipeline-core-services-docker-build:latest@sha256:3c01c83d966c90c4b0581704c56780eb6979a4cc23a02ffb037f491f91ad1147
      - name: name
        value: docker-build
      - name: kind
        value: Pipeline
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
